### ISSUE TITLE
Add "run benchmark" command support

### ISSUE THREAD

**Issue by bkontur** [paritytech/try-runtime-cli#73]
I am just thinking, as a part of [fellows repo issue](https://github.com/polkadot-fellows/runtimes/issues/50), I would like to add CI pipeline for testing "benchmarks" - like we have `short-benchmark*` jobs in `polkadot-sdk`.
Encointer was merged to fellows without even noticing that benchmarks do not work [see](https://github.com/polkadot-fellows/runtimes/issues/155).
We've merged `chain-spec-generator` to fellows, so the only puzzle missing is how to run them without need to rebuild `polkadot` binary in fellows CI. E.g. 

I think, there are two solutions:
1. release `polkadot` binary built with `--features runtime-benchmarks"
2. extend this `try-runtime-cli` - we are already using this binary for `check-migrations`, so maybe it could be possible to extend and just reuse this binary for running short benchmarks.

I think that testing/running benchmarks seems to be part of  "try runtime" functionality :)

**Comment by ggwpez** [comment]
> so the only puzzle missing is how to run them without need to rebuild polkadot binary in fellows CI. E.g.

Yea i thought about this. It should be possible to build the `benchmark pallet` command as freestanding binary that works with any runtime.   
But i dont see this as part of try-runtime. It can just be a freestanding bench runner binary.
For the other benchmarking commands its more difficult, since they actually use the node to author a block.

**Comment by liamaharon** [comment]
As @ggwpez mentioned, hopefully this will be added to the polkadot node soon.

Will try to keep `try-runtime` limited to operations related to calling into development runtime apis.
